name: Validate "Tested Up To"

on:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: write
  pull-requests: write
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Validate Plugin Version
        uses: jazzsequence/action-validate-plugin-version@754dfd0b2c86b788c3912c4b26a0e155acb5d2eb # v2.0.2