name: Draft Release PR
on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  draft-release:
    name: Draft Release PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Create Draft Release PR
        uses: pantheon-systems/plugin-release-actions/release-pr@554b455c9cb024ccf20147a27656fb198ce6f0cc # main 2025-11-07T23:23:14Z
        with:
          gh_token: ${{ github.token }}
          readme_md: README.md
