name: Draft Release PR
on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  draft-release:
    name: Draft Release PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Create Draft Release PR
        uses: pantheon-systems/plugin-release-actions/release-pr@8c76f0613b094d9812da9257030e534c4d8eeb6c # v0.5.6
        with:
          gh_token: ${{ github.token }}
          readme_md: README.md
