# On push, run the action-wporg-validator workflow.
name: WP.org Validator
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  validate:
    name: Validate Plugin
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Setup PHP 8.4
      uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
      with:
        php-version: "8.4"
        extensions: mysqli
        tools: composer,wp-cli

    - name: Cache Composer dependencies
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: |
            ~/.composer/cache
            vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
            ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --no-dev --no-interaction --no-progress --prefer-dist --no-scripts --no-ansi

    - name: Create Dist Archive for wp.org validation
      run: |
        wp package install wp-cli/dist-archive-command
        wp dist-archive . --plugin-dirname=wp-redis --filename-format=wp-redis-dist
        unzip ../wp-redis-dist.zip

    - name: Run plugin check
      uses: wordpress/plugin-check-action@70f38272b2beee386e973f319591baa2fc7dff16 # 1.1.2
      with:
        build-dir: wp-redis