name: WP.org Validator
on:
  pull_request:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  validate:
    name: Validate Plugin
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
    - name: Setup PHP 8.4
      uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
      with:
        php-version: "8.4"
        extensions: mysqli
        tools: composer,wp-cli

    - name: Cache Composer dependencies
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
            ~/.composer/cache
            vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
            ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --no-dev --no-interaction --no-progress --prefer-dist --no-scripts --no-ansi

    - name: Create Dist Archive for wp.org validation
      env:
        COMPOSER_AUTH: '{"github-oauth": {}}'
      run: |
        rm -f ~/.composer/auth.json
        wp package install wp-cli/dist-archive-command:v3.1.0
        wp dist-archive . --plugin-dirname=wp-redis --filename-format=wp-redis-dist
        unzip ../wp-redis-dist.zip

    - name: Run plugin check
      uses: wordpress/plugin-check-action@6f5a57e173c065a394b78688f75df543e4011902
      with:
        build-dir: wp-redis